# version: "3.9"

services:
  # API Gateway
  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - book-service
    restart: unless-stopped
    networks:
      - microservices-network

  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
      target: development
    container_name: book-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./book-service:/app
      - /app/node_modules
      - book-service-cache:/app/.cache
    restart: unless-stopped
    networks:
      - microservices-network
    command: npm run start:dev

networks:
  microservices-network:
    driver: bridge

volumes:
  book-service-cache:
    driver: local